// Generated by gencpp from file udemy_cpp_pkg/CameraRequest.msg
// DO NOT EDIT!


#ifndef UDEMY_CPP_PKG_MESSAGE_CAMERAREQUEST_H
#define UDEMY_CPP_PKG_MESSAGE_CAMERAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udemy_cpp_pkg
{
template <class ContainerAllocator>
struct CameraRequest_
{
  typedef CameraRequest_<ContainerAllocator> Type;

  CameraRequest_()
    : angle(0)  {
    }
  CameraRequest_(const ContainerAllocator& _alloc)
    : angle(0)  {
  (void)_alloc;
    }



   typedef int32_t _angle_type;
  _angle_type angle;





  typedef boost::shared_ptr< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> const> ConstPtr;

}; // struct CameraRequest_

typedef ::udemy_cpp_pkg::CameraRequest_<std::allocator<void> > CameraRequest;

typedef boost::shared_ptr< ::udemy_cpp_pkg::CameraRequest > CameraRequestPtr;
typedef boost::shared_ptr< ::udemy_cpp_pkg::CameraRequest const> CameraRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator2> & rhs)
{
  return lhs.angle == rhs.angle;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator1> & lhs, const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace udemy_cpp_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "de62f7ef8463d5c42dacb6932cbd1470";
  }

  static const char* value(const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xde62f7ef8463d5c4ULL;
  static const uint64_t static_value2 = 0x2dacb6932cbd1470ULL;
};

template<class ContainerAllocator>
struct DataType< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udemy_cpp_pkg/CameraRequest";
  }

  static const char* value(const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 angle\n"
;
  }

  static const char* value(const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udemy_cpp_pkg::CameraRequest_<ContainerAllocator>& v)
  {
    s << indent << "angle: ";
    Printer<int32_t>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDEMY_CPP_PKG_MESSAGE_CAMERAREQUEST_H
