// Generated by gencpp from file udemy_cpp_pkg/Camera.msg
// DO NOT EDIT!


#ifndef UDEMY_CPP_PKG_MESSAGE_CAMERA_H
#define UDEMY_CPP_PKG_MESSAGE_CAMERA_H

#include <ros/service_traits.h>


#include <udemy_cpp_pkg/CameraRequest.h>
#include <udemy_cpp_pkg/CameraResponse.h>


namespace udemy_cpp_pkg
{

struct Camera
{

typedef CameraRequest Request;
typedef CameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Camera
} // namespace udemy_cpp_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::udemy_cpp_pkg::Camera > {
  static const char* value()
  {
    return "4d104955aea5eb62c3dd701126361acc";
  }

  static const char* value(const ::udemy_cpp_pkg::Camera&) { return value(); }
};

template<>
struct DataType< ::udemy_cpp_pkg::Camera > {
  static const char* value()
  {
    return "udemy_cpp_pkg/Camera";
  }

  static const char* value(const ::udemy_cpp_pkg::Camera&) { return value(); }
};


// service_traits::MD5Sum< ::udemy_cpp_pkg::CameraRequest> should match
// service_traits::MD5Sum< ::udemy_cpp_pkg::Camera >
template<>
struct MD5Sum< ::udemy_cpp_pkg::CameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::udemy_cpp_pkg::Camera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::CameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::udemy_cpp_pkg::CameraRequest> should match
// service_traits::DataType< ::udemy_cpp_pkg::Camera >
template<>
struct DataType< ::udemy_cpp_pkg::CameraRequest>
{
  static const char* value()
  {
    return DataType< ::udemy_cpp_pkg::Camera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::CameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::udemy_cpp_pkg::CameraResponse> should match
// service_traits::MD5Sum< ::udemy_cpp_pkg::Camera >
template<>
struct MD5Sum< ::udemy_cpp_pkg::CameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::udemy_cpp_pkg::Camera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::CameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::udemy_cpp_pkg::CameraResponse> should match
// service_traits::DataType< ::udemy_cpp_pkg::Camera >
template<>
struct DataType< ::udemy_cpp_pkg::CameraResponse>
{
  static const char* value()
  {
    return DataType< ::udemy_cpp_pkg::Camera >::value();
  }
  static const char* value(const ::udemy_cpp_pkg::CameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UDEMY_CPP_PKG_MESSAGE_CAMERA_H
